### ISSUE TITLE
ImportError: cannot import name getOrTrainModel

### ISSUE THREAD

**Issue by flyingbrike** [driemworks/mynt#1]
Hello, i am a newbee.
When i try to run app.py , i get an arror :+1: ImportError: cannot import name getOrTrainModel
Pip installed mynt and sklearn ...scikit-learn
What is wrong?

**Comment by flyingbrike** [comment]
Thanks for the reply.
Not working yet.

This is the output:
erik@traderstation:~/python/mynt-master$ python setup.py sdist
running sdist
running check
warning: check: missing required meta-data: url

warning: sdist: manifest template 'MANIFEST.in' does not exist (using default file list)

warning: sdist: standard file not found: should have one of README, README.txt

package init file '__init__.py' not found (or not a regular file)
writing manifest file 'MANIFEST'
creating Mynt-1.0-dev
making hard links in Mynt-1.0-dev...
hard linking AlphaVantageGateway.py -> Mynt-1.0-dev
hard linking DataUtils.py -> Mynt-1.0-dev
hard linking NetworkUtils.py -> Mynt-1.0-dev
hard linking mynt.py -> Mynt-1.0-dev
hard linking setup.py -> Mynt-1.0-dev
Creating tar archive
removing 'Mynt-1.0-dev' (and everything under it)
erik@traderstation:~/python/mynt-master$ pip install ./dist/Mynt-1.0-dev.tar.gz
Processing ./dist/Mynt-1.0-dev.tar.gz
Building wheels for collected packages: Mynt
  Running setup.py bdist_wheel for Mynt ... done
  Stored in directory: /home/erik/.cache/pip/wheels/5f/54/d5/264274e6cab32ff917b3d6e511b19371e2a0e2cc2cff0ddcb8
Successfully built Mynt
Installing collected packages: Mynt
  Found existing installation: mynt 0.3.1
    Uninstalling mynt-0.3.1:
      Successfully uninstalled mynt-0.3.1
Successfully installed Mynt-1.0.dev0
erik@traderstation:~/python/mynt-master$ ls
AlphaVantageGateway.py  dist      LICENSE   mynt.py          readme.md         resources
DataUtils.py            examples  MANIFEST  NetworkUtils.py  requirements.txt  setup.py
erik@traderstation:~/python/mynt-master$ cd examples/
erik@traderstation:~/python/mynt-master/examples$ ls
app.py  __init__.py  resources
erik@traderstation:~/python/mynt-master/examples$ python app.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "app.py", line 19, in <module>
    model_data, weights_data, epochs=epochs, look_back=look_back)
  File "/home/erik/miniconda2/lib/python2.7/site-packages/mynt.py", line 41, in getOrTrainModel
    dataframe = avg.get_alpha_vantage_data(api_key, ticker, alphavantage_data_path)
  File "/home/erik/miniconda2/lib/python2.7/site-packages/AlphaVantageGateway.py", line 21, in get_alpha_vantage_data
    data = pickle.load(f)
  File "/home/erik/miniconda2/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/home/erik/miniconda2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/erik/miniconda2/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 4

**Comment by flyingbrike** [comment]
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19) 
[GCC 7.3.0] on linux2

**Comment by driemworks** [comment]
The pickle protocol 4 requires python version 3.4 or higher. In fact, I believe that tensorflow needs python 3.5 or higher. Can you try again using python 3.5+?

**Comment by flyingbrike** [comment]
ok, will try.

Name for your project.... PreTick...
As the famous Pre Cogs that predict future murders ...

2018-12-30 20:46 GMT, Tony Riemer <notifications@github.com>:
> The pickle protocol 4 requires python version 3.4 or higher. In fact, I
> believe that tensorflow needs python 3.5 or higher. Can you try again using
> python 3.5+?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/driemworks/mynt/issues/1#issuecomment-450585531


-- 
Vanwege
Erik Van Nieuwenhove
Hunnegemstraat 12
B-9500 Geraardsbergen
Belgie Oost-Vlaanderen
Tel. 0032 475701549
Btw BE.0887.244.845
KEYTRADEBANK : BE87 6511 3701 1694
BIC KEYTBEBBXXX
www.windtoys.be
www.windtech.be
www.braintuning.be
skype : flyingbrike

**Comment by flyingbrike** [comment]
Problems getting the dependencies installed:
I get errors on multible items: buildozer darkflow kivy  ....

(VENV3.6) erik@traderstation:~/VENV3.6/mynt-master$ pip3 install -r
requirements.txt
Collecting alabaster==0.7.12 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl
Collecting asn1crypto==0.22.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/97/ba/7e8117d8efcee589f4d96dd2b2eb1d997f96d27d214cf2b7134ad8acf6ab/asn1crypto-0.22.0-py2.py3-none-any.whl
Collecting astor==0.6.2 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/b2/91/cc9805f1ff7b49f620136b3a7ca26f6a1be2ed424606804b0fbcf499f712/astor-0.6.2-py2.py3-none-any.whl
Collecting Babel==2.6.0 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/b8/ad/c6f60602d3ee3d92fbed87675b6fb6a6f9a38c223343ababdb44ba201f10/Babel-2.6.0-py2.py3-none-any.whl
Collecting backports.weakref==1.0rc1 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/6a/f7/ae34b6818b603e264f26fe7db2bd07850ce331ce2fde74b266d61f4a2d87/backports.weakref-1.0rc1-py3-none-any.whl
Requirement already satisfied: beautifulsoup4==4.6.0 in
/usr/lib/python3/dist-packages (from -r requirements.txt (line 6))
Collecting bleach==1.5.0 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/33/70/86c5fec937ea4964184d4d6c4f0b9551564f821e1c3575907639036d9b90/bleach-1.5.0-py2.py3-none-any.whl
Requirement already satisfied: blinker==1.4 in
/usr/lib/python3/dist-packages (from -r requirements.txt (line 8))
Collecting certifi==2017.7.27.1 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/40/66/06130724e8205fc8c105db7edb92871c7fff7d31324d7f4405c762624a43/certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting cffi==1.10.0 (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/99/2f/2304b68ee2eea8395fb98702077e667849b98b9037956fafbef65fd53e0b/cffi-1.10.0-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: chardet==3.0.4 in
/home/erik/.local/lib/python3.6/site-packages (from -r
requirements.txt (line 11))
Collecting click==6.7 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Collecting colorama==0.4.1 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting cryptography==1.9 (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/2a/0c/31bd69469e90035381f0197b48bf71032991d9f07a7e444c311b4a23a3df/cryptography-1.9.tar.gz
Requirement already satisfied: cycler==0.10.0 in
/home/erik/.local/lib/python3.6/site-packages (from -r
requirements.txt (line 15))
Collecting Cython==0.26.1 (from -r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/a0/f6/3927706fef7b6a191b2274a6f74416f47d2fecb8bacd8341c634c02f7b30/Cython-0.26.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting decorator==4.3.0 (from -r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
Collecting docopt==0.6.2 (from -r requirements.txt (line 18))
  Using cached https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting docutils==0.14 (from -r requirements.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl
Collecting enum34==1.1.6 (from -r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/af/42/cb9355df32c69b553e72a2e28daee25d1611d2c0d9c272aa1d34204205b2/enum34-1.1.6-py3-none-any.whl
Collecting Flask==0.12.2 (from -r requirements.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/77/32/e3597cb19ffffe724ad4bf0beca4153419918e7fa4ba6a34b04ee4da3371/Flask-0.12.2-py2.py3-none-any.whl
Collecting Flask-Mail==0.9.1 (from -r requirements.txt (line 22))
  Using cached https://files.pythonhosted.org/packages/05/2f/6a545452040c2556559779db87148d2a85e78a26f90326647b51dc5e81e9/Flask-Mail-0.9.1.tar.gz
Collecting Flask-WTF==0.12 (from -r requirements.txt (line 23))
  Using cached https://files.pythonhosted.org/packages/f6/fe/9fe6a8a4edcc39f8ec365dc16d292d659f7a77a0ed596947f29c0c5c9dc1/Flask-WTF-0.12.tar.gz
Collecting future==0.16.0 (from -r requirements.txt (line 24))
  Using cached https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz
Collecting gsw==3.2.0 (from -r requirements.txt (line 25))
  Using cached https://files.pythonhosted.org/packages/1d/43/fc490809db7ad4d8665476c3a8ff3c3797c8b40347661ae5c233edf908f8/gsw-3.2.0.tar.gz
Collecting gym==0.10.5 (from -r requirements.txt (line 26))
  Using cached https://files.pythonhosted.org/packages/9b/50/ed4a03d2be47ffd043be2ee514f329ce45d98a30fe2d1b9c61dea5a9d861/gym-0.10.5.tar.gz
Collecting h5py==2.7.1 (from -r requirements.txt (line 27))
  Using cached https://files.pythonhosted.org/packages/f2/b8/a63fcc840bba5c76e453dd712dbca63178a264c8990e0086b72965d4e954/h5py-2.7.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting html5lib==0.9999999 (from -r requirements.txt (line 28))
  Using cached https://files.pythonhosted.org/packages/ae/ae/bcb60402c60932b32dfaf19bb53870b29eda2cd17551ba5639219fb5ebf9/html5lib-0.9999999.tar.gz
Collecting IbPy2==0.8.0 (from -r requirements.txt (line 29))
  Using cached https://files.pythonhosted.org/packages/63/75/98a31bebdbd90ef6ca1769d690bbc52c4e2557ea19dcce150c4c8147e02e/IbPy2-0.8.0.tar.gz
Obtaining IBroke from
git+https://gitlab.com/doctorj/ibroke.git@dcb04b49b5135b9c38e7721f45ce0ce76b8b0d2d#egg=IBroke
(from -r requirements.txt (line 30))
  Skipping because already up-to-date.
Collecting idna==2.5 (from -r requirements.txt (line 31))
  Using cached https://files.pythonhosted.org/packages/11/7d/9bbbd7bb35f34b0169542487d2a8859e44306bb2e6a4455d491800a5621f/idna-2.5-py2.py3-none-any.whl
Collecting imagesize==1.1.0 (from -r requirements.txt (line 32))
  Using cached https://files.pythonhosted.org/packages/fc/b6/aef66b4c52a6ad6ac18cf6ebc5731ed06d8c9ae4d3b2d9951f261150be67/imagesize-1.1.0-py2.py3-none-any.whl
Collecting imutils==0.4.3 (from -r requirements.txt (line 33))
  Using cached https://files.pythonhosted.org/packages/a0/cf/5f19a892b73c1992b83fbe747556984e68b2c04a3967ab52ef093d89f929/imutils-0.4.3.tar.gz
Requirement already satisfied: inflection==0.3.1 in
/home/erik/.local/lib/python3.6/site-packages (from -r
requirements.txt (line 34))
Collecting itsdangerous==0.24 (from -r requirements.txt (line 35))
  Using cached https://files.pythonhosted.org/packages/dc/b4/a60bcdba945c00f6d608d8975131ab3f25b22f2bcfe1dab221165194b2d4/itsdangerous-0.24.tar.gz
Requirement already satisfied: Jinja2==2.10 in
/home/erik/.local/lib/python3.6/site-packages (from -r
requirements.txt (line 36))
Collecting Keras==2.1.5 (from -r requirements.txt (line 37))
  Using cached https://files.pythonhosted.org/packages/ba/65/e4aff762b8696ec0626a6654b1e73b396fcc8b7cc6b98d78a1bc53b85b48/Keras-2.1.5-py2.py3-none-any.whl
Collecting keras-rl==0.4.2 (from -r requirements.txt (line 38))
  Using cached https://files.pythonhosted.org/packages/ab/87/4b57eff8e4bd834cea0a75cd6c58198c9e42be29b600db9c14fafa72ec07/keras-rl-0.4.2.tar.gz
Collecting Kivy==1.10.0 (from -r requirements.txt (line 39))
  Using cached https://files.pythonhosted.org/packages/8c/49/5c22589099f9b7fd106502ee6634a6675e634d7553fede141a7606e6a92d/Kivy-1.10.0.tar.gz
Collecting Kivy-Garden==0.1.4 (from -r requirements.txt (line 40))
  Downloading https://files.pythonhosted.org/packages/7d/68/decaee596ff8168a39432eb3949fc7c0be952ebb9467806823bffc165d48/kivy-garden-0.1.4.tar.gz
Collecting kivy.deps.angle==0.1.6 (from -r requirements.txt (line 41))
  Could not find a version that satisfies the requirement
kivy.deps.angle==0.1.6 (from -r requirements.txt (line 41)) (from
versions: )
No matching distribution found for kivy.deps.angle==0.1.6 (from -r
requirements.txt (line 41))

2018-12-30 20:46 GMT, Tony Riemer <notifications@github.com>:
> The pickle protocol 4 requires python version 3.4 or higher. In fact, I
> believe that tensorflow needs python 3.5 or higher. Can you try again using
> python 3.5+?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/driemworks/mynt/issues/1#issuecomment-450585531


-- 
Vanwege
Erik Van Nieuwenhove
Hunnegemstraat 12
B-9500 Geraardsbergen
Belgie Oost-Vlaanderen
Tel. 0032 475701549
Btw BE.0887.244.845
KEYTRADEBANK : BE87 6511 3701 1694
BIC KEYTBEBBXXX
www.windtoys.be
www.windtech.be
www.braintuning.be
skype : flyingbrike

**Comment by driemworks** [comment]
Some dependencies that are not needed were in the requirements.txt file (kivy being one of them). I've updated the requirements.txt to only include what is needed, as well as a conda environment file that you can use to load an environment with all needed dependencies (if you use anaconda) in resources/conda.

**Comment by flyingbrike** [comment]
Ok, it is running.
Now i will try to learn howto  use it.
Thanks for the help.

2018-12-30 22:13 GMT, Tony Riemer <notifications@github.com>:
> Some dependencies that are not needed were in the requirements.txt file
> (kivy being one of them). I've updated the requirements.txt to only include
> what is needed, as well as a conda environment file that you can use to load
> an environment with all needed dependencies (if you use anaconda) in
> resources/conda.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/driemworks/mynt/issues/1#issuecomment-450590287


-- 
Vanwege
Erik Van Nieuwenhove
Hunnegemstraat 12
B-9500 Geraardsbergen
Belgie Oost-Vlaanderen
Tel. 0032 475701549
Btw BE.0887.244.845
KEYTRADEBANK : BE87 6511 3701 1694
BIC KEYTBEBBXXX
www.windtoys.be
www.windtech.be
www.braintuning.be
skype : flyingbrike
